Repository NioDev01/mei-2-me, pull requests merged in 2025-07, with the labels that each got.

#10 docs(api): configure Swagger for API documentation
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
  server/src/main.ts
Labels: feature, back-end

#19 style: configure Prettier file
  server/.prettierrc
Labels: documentação, feature

#24 Feat: create ToggleTemas
  client/index.html
  client/src/features/NavBarMain.tsx
  client/src/features/ToggleTemas.tsx
Labels: feature, front-end

#23 feat: create AnaliseMigracao module
  server/src/app.module.ts
  server/src/modules/analise-migracao/analise-migracao.module.ts
  server/src/modules/analise-migracao/analise-migracao.service.spec.ts
  server/src/modules/analise-migracao/analise-migracao.service.ts
  server/src/modules/analise-migracao/rules/faturamento-anual.rule.ts
Labels: back-end

#29 Feat: Update Banco de dados Inativar modulo diagnostico provisoriamente
  server/src/app.module.ts
  server/src/modules/diagnostico-inicial/diagnostico-inicial.controller.spec.ts
  server/src/modules/diagnostico-inicial/diagnostico-inicial.controller.ts
  server/src/modules/diagnostico-inicial/diagnostico-inicial.module.ts
  server/src/modules/diagnostico-inicial/diagnostico-inicial.service.spec.ts
  server/src/modules/diagnostico-inicial/diagnostico-inicial.service.ts
  server/src/modules/diagnostico-inicial/dto/create-diagnostico-inicial.dto.ts
  server/src/modules/diagnostico-inicial/dto/update-diagnostico-inicial.dto.ts
  server/src/modules/diagnostico-inicial/entities/diagnostico-inicial.entity.ts
Labels: feature, database
